# Generated by Django 5.1.1 on 2025-05-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0006_rename_browser_info_clickanalytics_browser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='original_url',
            field=models.URLField(max_length=4000),
        ),
    ]
